### ISSUE TITLE
Numbers: need access to entity.resolution.value

### ISSUE THREAD

**Issue by spacether** [wiseman/pyluis#1]
https://docs.microsoft.com/en-us/azure/cognitive-services/LUIS/pre-builtentities
Number are now sometimes reported as u'2', sometimes as u'two'
When they are reported as u'two' we need to access entity.resolution.value to get to the u'2' value.

**Comment by spacether** [comment]
I submitted a pull request to address this:
https://github.com/wiseman/pyluis/pull/2
The testing throws an error in python 3.2. The error is in urllib3/contrib/pyopenssl.py
and this page: https://stackoverflow.com/questions/43813086/python-pyopenssl-syntax-error-at-import
says that requests no longer is supported in python 3.2

Removed Python 3.2 from .travis.yml file

**Comment by spacether** [comment]
Removed Python 3.2 from .travis.yml file

**Comment by wiseman** [comment]
Merged, thanks!
